version: "3.2"
services:
  volumes:
    pgdata:
        driver: local

services:
   test-db:
      restart: unless-stopped
      container_name: test-db
      image: postgres
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: '123456'
         POSTGRES_DB: netdb
         PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
         - ./pgdata/:/var/lib/postgresql/data/pgdata
      ports:
         - 5432:5432

   test-server:
      restart: unless-stopped
      container_name: test-server
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 8000:8000
      command: "bash entrypoint.sh"
      env_file:
         - env.conf
      links:
         - test-db

   test-nginx:
      restart: unless-stopped
      container_name: test-nginx
      image: nginx
      expose:
         - 8080
      ports:
         - 8080:8080
      volumes:
         - ./nginx/static/:/srv/www/server/static/
         - ./nginx/logs:/srv/www/server/logs
         - ./nginx-server.conf:/etc/nginx/conf.d/default.conf
      links:
         - test-server